import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/components/LoginBtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/components/LogoutBtn";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {

    let session  = await getServerSession(authOptions)
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <div className="navbar">
                <Link href="/" className="logo">Appleforum</Link>
                <Link href="/list">List</Link>
                <Link href="/write">write</Link>
                {
                    session == null ?
                        <> <Link href={"/register"}>회원가입</Link><LoginBtn/> </>
                        : <LogoutBtn/>
                }
            </div>
        {children}
        </body>
        </html>
    );
}
