import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/components/LoginBtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/components/LogoutBtn";
import Darkmode from "@/components/Darkmode";
import {cookies} from "next/headers";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {

    let session  = await getServerSession(authOptions);

    let res = cookies().get('dark-mode');

    return (
        <html lang="en">
        <body className={ res?.value === 'dark' ? 'dark-mode' : ''}>
            <div className="navbar">
                <Link href="/" className="logo">Appleforum</Link>
                <Link href="/list">List</Link>
                <Link href="/write">write</Link>
                {
                    session == null ?
                        <> <Link href={"/register"}>회원가입</Link><LoginBtn/> </>
                        : <LogoutBtn/>
                }
                <Darkmode darkmode={res?.value}/>
            </div>
        {children}
        </body>
        </html>
    );
}
